### ISSUE TITLE
stoping after warning,plz fix

### ISSUE THREAD

**Issue by tutumeme** [rastaayoub/BCHCLICKBOT#2]
bot stops after this error:this is telethon error but bot shouldn't completely stop:

WARNING:telethon.network.mtprotosender:Security error while unpacking a received message: Server replied with a wrong session ID

**Comment by rastaayoub** [comment]
hey , i'm sorty for that but there is some errors than never handled with the bot . you can restart it . this error comes because of a fake task in the Bchclick_bot .
